name: CI/CD pipeline

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checando o código
    uses: actions/checkout@v2

    - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
    python-version: '3.9'

    - name: Install dependencies
    	run: |
      	python -m venv venv
      	. venv/bin/activate
      	pip install -r requirements.txt
      	pip install pytest pytest-flask

  	- name: Run tests
    	run: |
      	. venv/bin/activate
      	pytest

